apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechITFactory/techitfactory-gitops.git
    targetRevision: main
    path: environments/dev/user-service
  destination:
    server: https://kubernetes.default.svc
    namespace: techitfactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
